services:
  lemma:
    hostname: lemma
    mem_limit: 768m
    image: "markmdev/python_lemmas"
  backend:
    hostname: backend
    mem_limit: 768m
    image: "markmdev/compinput-backend"
    command: npm run start
    environment:
      - SUPABASE_URL=$SUPABASE_URL
      - SUPABASE_SERVICE_API_KEY=$SUPABASE_SERVICE_API_KEY
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - JWT_SECRET=$JWT_SECRET
      - DATABASE_URL=$DATABASE_URL
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - APP_PORT=4000
      - LEMMA_SERVICE_URL=http://lemma:8000
  worker:
    hostname: worker
    mem_limit: 768m
    image: "markmdev/compinput-worker"
    command: npm run worker
    environment:
      - SUPABASE_URL=$SUPABASE_URL
      - SUPABASE_SERVICE_API_KEY=$SUPABASE_SERVICE_API_KEY
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - JWT_SECRET=$JWT_SECRET
      - DATABASE_URL=$DATABASE_URL
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - APP_PORT=4000
      - LEMMA_SERVICE_URL=http://lemma:8000
    depends_on:
      - backend
  frontend:
    hostname: frontend
    mem_limit: 1024m
    image: "markmdev/compinput-frontend"
    depends_on:
      - backend
  nginx:
    mem_limit: 128m
    hostname: nginx
    image: "markmdev/compinput-nginx"
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
