services:
  nginx:
    mem_limit: 128m
    hostname: nginx
    restart: always
    image: "markmdev/compinput-nginx"
    ports:
      - "80:80"
  lemma:
    hostname: lemma
    mem_limit: 256m
    image: "markmdev/python_lemmas"
  backend:
    hostname: backend
    mem_limit: 512m
    image: "markmdev/compinput-backend"
    command: npm run start
    environment:
      - SUPABASE_URL=$SUPABASE_URL
      - SUPABASE_SERVICE_API_KEY=$SUPABASE_SERVICE_API_KEY
      - PORT=$PORT
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - JWT_SECRET=$JWT_SECRET
      - LEMMA_SERVICE_URL=$LEMMA_SERVICE_URL
      - FRONTEND_URL=$FRONTEND_URL
      - REDIS_URL=$REDIS_URL
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_STRING=$REDIS_STRING
      - DATABASE_URL=$DATABASE_URL
  worker:
    hostname: worker
    mem_limit: 384m
    image: "markmdev/compinput-worker"
    command: npm run worker
    environment:
      - SUPABASE_URL=$SUPABASE_URL
      - SUPABASE_SERVICE_API_KEY=$SUPABASE_SERVICE_API_KEY
      - PORT=$PORT
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - JWT_SECRET=$JWT_SECRET
      - LEMMA_SERVICE_URL=$LEMMA_SERVICE_URL
      - FRONTEND_URL=$FRONTEND_URL
      - REDIS_URL=$REDIS_URL
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_STRING=$REDIS_STRING
      - DATABASE_URL=$DATABASE_URL
  frontend:
    hostname: frontend
    mem_limit: 256m
    image: "markmdev/compinput-frontend"
